# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys



class Ui_qtSCC(object):

    def setupUi(self, qtSCC):
        qtSCC.setObjectName("qtSCC")
        qtSCC.resize(800, 600)
        self.verticalLayoutWidget = QtWidgets.QWidget(qtSCC)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 781, 581))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.inputEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.inputEdit.setReadOnly(False)
        self.inputEdit.setObjectName("inputEdit")
        self.horizontalLayout_2.addWidget(self.inputEdit)
        self.SearchButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.SearchButton.setObjectName("SearchButton")
        self.horizontalLayout_2.addWidget(self.SearchButton)
        self.assembleButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.assembleButton.setObjectName("assembleButton")
        self.horizontalLayout_2.addWidget(self.assembleButton)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fileList = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.fileList.setObjectName("fileList")
        self.horizontalLayout.addWidget(self.fileList)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.translateList = QtWidgets.QListWidget(self.verticalLayoutWidget)
        self.translateList.setObjectName("translateList")
        self.verticalLayout_2.addWidget(self.translateList)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.saveEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.saveEdit.setObjectName("saveEdit")
        self.horizontalLayout_3.addWidget(self.saveEdit)
        self.saveButton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.saveButton.setObjectName("saveButton")
        self.horizontalLayout_3.addWidget(self.saveButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(qtSCC)
        QtCore.QMetaObject.connectSlotsByName(qtSCC)

    def retranslateUi(self, qtSCC):
        _translate = QtCore.QCoreApplication.translate
        qtSCC.setWindowTitle(_translate("qtSCC", "qtSCC"))
        self.SearchButton.setText(_translate("qtSCC", "Search"))
        self.assembleButton.setText(_translate("qtSCC", "Assemble"))
        self.saveButton.setText(_translate("qtSCC", "Save"))


